title: Introduction to Lithospheric Geodynamic Modelling
description: Home of the Introduction to Lithospheric Geodynamic Modelling course at the University of Helsinki
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
